-- Session telemetry — docs/plan/06-telemetry-upload.md
--
-- Three tables and one rule: the client can write and cannot read.
--
-- The thing being protected is not the numbers, it is the text. These sessions
-- contain business ideas someone typed in confidence and a model's reasoning
-- about them. So the schema separates what a cost comparison needs (tokens,
-- latency, model, outcome) from what only a quality review needs (the words),
-- and they are two tables with two consent decisions rather than one table with
-- a flag — a flag on a row is a thing that gets forgotten in a WHERE clause.

-- ---------------------------------------------------------------------------
-- sessions — one row per run. Metadata only; no free text.
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  -- Generated by the client so the upload is idempotent: a retry after a
  -- half-failed batch re-sends the same id and conflicts away.
  id             uuid primary key,
  -- Which build produced it. The first thing you filter on when a rate moves.
  build          text        not null,
  started_at     timestamptz not null,
  ended_at       timestamptz,
  -- 'committed' | 'abandoned' | 'unfinished'
  outcome        text        not null,
  -- Archetype rather than business name: it is the analytic dimension, and it
  -- is not identifying. The name is free text and lives in `transcripts`.
  archetype      text,
  start_capital  text,
  turns          integer     not null default 0,
  quarters       integer     not null default 0,
  -- Quality signals, denormalised so the common query needs no join.
  repair_rounds     integer  not null default 0,
  questions_asked   integer  not null default 0,
  fabricated_figures integer not null default 0,
  cancelled         integer  not null default 0,
  -- When the row arrived, set server-side. A client clock is not evidence.
  received_at    timestamptz not null default now()
);

comment on column public.sessions.fabricated_figures is
  'Times the advisor quoted money the ledger never produced and was re-asked. '
  'The §1.1 failure, and the quality signal a player cannot catch themselves.';

-- ---------------------------------------------------------------------------
-- calls — one row per model call, including the attempts that failed.
-- ---------------------------------------------------------------------------
create table if not exists public.calls (
  session_id     uuid        not null references public.sessions(id) on delete cascade,
  -- Position within the session. Together with session_id this is the key, so a
  -- retry of a partially-inserted batch does not duplicate rows.
  seq            integer     not null,
  -- 'turn' | 'draft' | 'advise' | 'adjudicate'
  call           text        not null,
  provider       text        not null,
  model          text        not null,
  effort         text        not null,
  ms             integer     not null,
  input_tokens        integer not null,
  cached_input_tokens integer not null,
  output_tokens       integer not null,
  thinking_tokens     integer not null,
  -- Priced at the call against the model that answered. `rates_known` false
  -- means the model was not in the price list and cost_usd is 0 rather than a
  -- guess — the tokens are here, so it can be repriced without replaying.
  cost_usd       numeric(12, 6) not null,
  rates_known    boolean     not null,
  attempt        integer     not null,
  ok             boolean     not null,
  failure        text,
  primary key (session_id, seq)
);

create index if not exists calls_model_idx on public.calls (model);
create index if not exists calls_call_idx  on public.calls (call);

-- ---------------------------------------------------------------------------
-- transcripts — the content tier. Separate consent, separate table.
-- ---------------------------------------------------------------------------
create table if not exists public.transcripts (
  session_id uuid        not null references public.sessions(id) on delete cascade,
  seq        integer     not null,
  -- The journal event kind: 'turn', 'draft', 'asked', 'objection', …
  kind       text        not null,
  -- The event verbatim. jsonb rather than columns because the journal's shape
  -- changes with the game and a migration per event kind would guarantee the
  -- schema lags what is being recorded.
  payload    jsonb       not null,
  primary key (session_id, seq)
);

comment on table public.transcripts is
  'Player-authored text and model reasoning. Uploaded only under a second, '
  'explicit opt-in — never implied by consent to the metrics tables.';

-- ---------------------------------------------------------------------------
-- Row-level security: the client writes and cannot read.
-- ---------------------------------------------------------------------------
--
-- The publishable key ships inside the game, so treat it as public. Under these
-- policies the worst a leaked key does is add rows: there is no select, update
-- or delete policy for `anon`, so it cannot read one player's session back, and
-- it cannot alter or remove anyone's. Analysis runs on the service role, which
-- stays server-side.
alter table public.sessions    enable row level security;
alter table public.calls       enable row level security;
alter table public.transcripts enable row level security;

drop policy if exists sessions_insert    on public.sessions;
drop policy if exists calls_insert       on public.calls;
drop policy if exists transcripts_insert on public.transcripts;

create policy sessions_insert    on public.sessions    for insert to anon with check (true);
create policy calls_insert       on public.calls       for insert to anon with check (true);
create policy transcripts_insert on public.transcripts for insert to anon with check (true);

-- Deliberately no policy granting select/update/delete to `anon`. Their absence
-- is the security property; adding one for convenience during analysis would
-- quietly make every session readable by anyone holding the shipped key.
